# coding: utf-8

"""
    Marketing API v.1.0

    IMPORTANT: This swagger links to Criteo production environment. Any test applied here will thus impact real campaigns.  # noqa: E501

    OpenAPI spec version: v.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class AudienceCreateRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'advertiser_id': 'int',
        'name': 'str',
        'description': 'str'
    }

    attribute_map = {
        'advertiser_id': 'advertiserId',
        'name': 'name',
        'description': 'description'
    }

    def __init__(self, advertiser_id=None, name=None, description=None):  # noqa: E501
        """AudienceCreateRequest - a model defined in OpenAPI"""  # noqa: E501

        self._advertiser_id = None
        self._name = None
        self._description = None
        self.discriminator = None

        if advertiser_id is not None:
            self.advertiser_id = advertiser_id
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description

    @property
    def advertiser_id(self):
        """Gets the advertiser_id of this AudienceCreateRequest.  # noqa: E501

        Mandatory. The AdvertiserId this Audience will belong to.  # noqa: E501

        :return: The advertiser_id of this AudienceCreateRequest.  # noqa: E501
        :rtype: int
        """
        return self._advertiser_id

    @advertiser_id.setter
    def advertiser_id(self, advertiser_id):
        """Sets the advertiser_id of this AudienceCreateRequest.

        Mandatory. The AdvertiserId this Audience will belong to.  # noqa: E501

        :param advertiser_id: The advertiser_id of this AudienceCreateRequest.  # noqa: E501
        :type: int
        """

        self._advertiser_id = advertiser_id

    @property
    def name(self):
        """Gets the name of this AudienceCreateRequest.  # noqa: E501

        Mandatory. The Audience Name.  # noqa: E501

        :return: The name of this AudienceCreateRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AudienceCreateRequest.

        Mandatory. The Audience Name.  # noqa: E501

        :param name: The name of this AudienceCreateRequest.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this AudienceCreateRequest.  # noqa: E501

        Optional description of the audience.  # noqa: E501

        :return: The description of this AudienceCreateRequest.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this AudienceCreateRequest.

        Optional description of the audience.  # noqa: E501

        :param description: The description of this AudienceCreateRequest.  # noqa: E501
        :type: str
        """

        self._description = description

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AudienceCreateRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
