# coding: utf-8

"""
    Marketing API v.1.0

    IMPORTANT: This swagger links to Criteo production environment. Any test applied here will thus impact real campaigns.  # noqa: E501

    The version of the OpenAPI document: v.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class CampaignBidChangeRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'campaign_id': 'int',
        'bid_value': 'float',
        'categories': 'list[CategoryBidChangeRequest]'
    }

    attribute_map = {
        'campaign_id': 'campaignId',
        'bid_value': 'bidValue',
        'categories': 'categories'
    }

    def __init__(self, campaign_id=None, bid_value=None, categories=None):  # noqa: E501
        """CampaignBidChangeRequest - a model defined in OpenAPI"""  # noqa: E501

        self._campaign_id = None
        self._bid_value = None
        self._categories = None
        self.discriminator = None

        if campaign_id is not None:
            self.campaign_id = campaign_id
        if bid_value is not None:
            self.bid_value = bid_value
        if categories is not None:
            self.categories = categories

    @property
    def campaign_id(self):
        """Gets the campaign_id of this CampaignBidChangeRequest.  # noqa: E501


        :return: The campaign_id of this CampaignBidChangeRequest.  # noqa: E501
        :rtype: int
        """
        return self._campaign_id

    @campaign_id.setter
    def campaign_id(self, campaign_id):
        """Sets the campaign_id of this CampaignBidChangeRequest.


        :param campaign_id: The campaign_id of this CampaignBidChangeRequest.  # noqa: E501
        :type: int
        """

        self._campaign_id = campaign_id

    @property
    def bid_value(self):
        """Gets the bid_value of this CampaignBidChangeRequest.  # noqa: E501


        :return: The bid_value of this CampaignBidChangeRequest.  # noqa: E501
        :rtype: float
        """
        return self._bid_value

    @bid_value.setter
    def bid_value(self, bid_value):
        """Sets the bid_value of this CampaignBidChangeRequest.


        :param bid_value: The bid_value of this CampaignBidChangeRequest.  # noqa: E501
        :type: float
        """

        self._bid_value = bid_value

    @property
    def categories(self):
        """Gets the categories of this CampaignBidChangeRequest.  # noqa: E501


        :return: The categories of this CampaignBidChangeRequest.  # noqa: E501
        :rtype: list[CategoryBidChangeRequest]
        """
        return self._categories

    @categories.setter
    def categories(self, categories):
        """Sets the categories of this CampaignBidChangeRequest.


        :param categories: The categories of this CampaignBidChangeRequest.  # noqa: E501
        :type: list[CategoryBidChangeRequest]
        """

        self._categories = categories

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CampaignBidChangeRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
