# coding: utf-8

"""
    Marketing API v.1.0

    IMPORTANT: This swagger links to Criteo production environment. Any test applied here will thus impact real campaigns.  # noqa: E501

    OpenAPI spec version: v.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class CategoryBidMessage(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'category_hashcode': 'int',
        'category_name': 'str',
        'category_bid': 'BidMessage'
    }

    attribute_map = {
        'category_hashcode': 'categoryHashcode',
        'category_name': 'categoryName',
        'category_bid': 'categoryBid'
    }

    def __init__(self, category_hashcode=None, category_name=None, category_bid=None):  # noqa: E501
        """CategoryBidMessage - a model defined in OpenAPI"""  # noqa: E501

        self._category_hashcode = None
        self._category_name = None
        self._category_bid = None
        self.discriminator = None

        if category_hashcode is not None:
            self.category_hashcode = category_hashcode
        if category_name is not None:
            self.category_name = category_name
        if category_bid is not None:
            self.category_bid = category_bid

    @property
    def category_hashcode(self):
        """Gets the category_hashcode of this CategoryBidMessage.  # noqa: E501


        :return: The category_hashcode of this CategoryBidMessage.  # noqa: E501
        :rtype: int
        """
        return self._category_hashcode

    @category_hashcode.setter
    def category_hashcode(self, category_hashcode):
        """Sets the category_hashcode of this CategoryBidMessage.


        :param category_hashcode: The category_hashcode of this CategoryBidMessage.  # noqa: E501
        :type: int
        """

        self._category_hashcode = category_hashcode

    @property
    def category_name(self):
        """Gets the category_name of this CategoryBidMessage.  # noqa: E501


        :return: The category_name of this CategoryBidMessage.  # noqa: E501
        :rtype: str
        """
        return self._category_name

    @category_name.setter
    def category_name(self, category_name):
        """Sets the category_name of this CategoryBidMessage.


        :param category_name: The category_name of this CategoryBidMessage.  # noqa: E501
        :type: str
        """

        self._category_name = category_name

    @property
    def category_bid(self):
        """Gets the category_bid of this CategoryBidMessage.  # noqa: E501


        :return: The category_bid of this CategoryBidMessage.  # noqa: E501
        :rtype: BidMessage
        """
        return self._category_bid

    @category_bid.setter
    def category_bid(self, category_bid):
        """Sets the category_bid of this CategoryBidMessage.


        :param category_bid: The category_bid of this CategoryBidMessage.  # noqa: E501
        :type: BidMessage
        """

        self._category_bid = category_bid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CategoryBidMessage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
