# coding: utf-8

"""
    Marketing API v.1.0

    IMPORTANT: This swagger links to Criteo production environment. Any test applied here will thus impact real campaigns.  # noqa: E501

    The version of the OpenAPI document: v.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ProductImporterBatch(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'entries': 'list[CatalogProductV3]'
    }

    attribute_map = {
        'entries': 'entries'
    }

    def __init__(self, entries=None):  # noqa: E501
        """ProductImporterBatch - a model defined in OpenAPI"""  # noqa: E501

        self._entries = None
        self.discriminator = None

        if entries is not None:
            self.entries = entries

    @property
    def entries(self):
        """Gets the entries of this ProductImporterBatch.  # noqa: E501

        The request entries to be processed in the batch.  # noqa: E501

        :return: The entries of this ProductImporterBatch.  # noqa: E501
        :rtype: list[CatalogProductV3]
        """
        return self._entries

    @entries.setter
    def entries(self, entries):
        """Sets the entries of this ProductImporterBatch.

        The request entries to be processed in the batch.  # noqa: E501

        :param entries: The entries of this ProductImporterBatch.  # noqa: E501
        :type: list[CatalogProductV3]
        """

        self._entries = entries

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProductImporterBatch):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
