# coding: utf-8

"""
    Marketing API v.1.0

    IMPORTANT: This swagger links to Criteo production environment. Any test applied here will thus impact real campaigns.  # noqa: E501

    OpenAPI spec version: v.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class PublisherFileStatsMessage(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'file_name': 'str',
        'token_valid_until': 'datetime',
        'url': 'str'
    }

    attribute_map = {
        'file_name': 'fileName',
        'token_valid_until': 'tokenValidUntil',
        'url': 'url'
    }

    def __init__(self, file_name=None, token_valid_until=None, url=None):  # noqa: E501
        """PublisherFileStatsMessage - a model defined in OpenAPI"""  # noqa: E501

        self._file_name = None
        self._token_valid_until = None
        self._url = None
        self.discriminator = None

        if file_name is not None:
            self.file_name = file_name
        if token_valid_until is not None:
            self.token_valid_until = token_valid_until
        if url is not None:
            self.url = url

    @property
    def file_name(self):
        """Gets the file_name of this PublisherFileStatsMessage.  # noqa: E501


        :return: The file_name of this PublisherFileStatsMessage.  # noqa: E501
        :rtype: str
        """
        return self._file_name

    @file_name.setter
    def file_name(self, file_name):
        """Sets the file_name of this PublisherFileStatsMessage.


        :param file_name: The file_name of this PublisherFileStatsMessage.  # noqa: E501
        :type: str
        """

        self._file_name = file_name

    @property
    def token_valid_until(self):
        """Gets the token_valid_until of this PublisherFileStatsMessage.  # noqa: E501


        :return: The token_valid_until of this PublisherFileStatsMessage.  # noqa: E501
        :rtype: datetime
        """
        return self._token_valid_until

    @token_valid_until.setter
    def token_valid_until(self, token_valid_until):
        """Sets the token_valid_until of this PublisherFileStatsMessage.


        :param token_valid_until: The token_valid_until of this PublisherFileStatsMessage.  # noqa: E501
        :type: datetime
        """

        self._token_valid_until = token_valid_until

    @property
    def url(self):
        """Gets the url of this PublisherFileStatsMessage.  # noqa: E501


        :return: The url of this PublisherFileStatsMessage.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this PublisherFileStatsMessage.


        :param url: The url of this PublisherFileStatsMessage.  # noqa: E501
        :type: str
        """

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PublisherFileStatsMessage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
