# coding: utf-8

"""
    Marketing API v.1.0

    IMPORTANT: This swagger links to Criteo production environment. Any test applied here will thus impact real campaigns.  # noqa: E501

    OpenAPI spec version: v.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class RoutePolicy(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'policy_route_info': 'PolicyRouteInfo',
        'throttle_policy': 'ThrottlePolicy'
    }

    attribute_map = {
        'policy_route_info': 'policyRouteInfo',
        'throttle_policy': 'throttlePolicy'
    }

    def __init__(self, policy_route_info=None, throttle_policy=None):  # noqa: E501
        """RoutePolicy - a model defined in OpenAPI"""  # noqa: E501

        self._policy_route_info = None
        self._throttle_policy = None
        self.discriminator = None

        if policy_route_info is not None:
            self.policy_route_info = policy_route_info
        if throttle_policy is not None:
            self.throttle_policy = throttle_policy

    @property
    def policy_route_info(self):
        """Gets the policy_route_info of this RoutePolicy.  # noqa: E501


        :return: The policy_route_info of this RoutePolicy.  # noqa: E501
        :rtype: PolicyRouteInfo
        """
        return self._policy_route_info

    @policy_route_info.setter
    def policy_route_info(self, policy_route_info):
        """Sets the policy_route_info of this RoutePolicy.


        :param policy_route_info: The policy_route_info of this RoutePolicy.  # noqa: E501
        :type: PolicyRouteInfo
        """

        self._policy_route_info = policy_route_info

    @property
    def throttle_policy(self):
        """Gets the throttle_policy of this RoutePolicy.  # noqa: E501


        :return: The throttle_policy of this RoutePolicy.  # noqa: E501
        :rtype: ThrottlePolicy
        """
        return self._throttle_policy

    @throttle_policy.setter
    def throttle_policy(self, throttle_policy):
        """Sets the throttle_policy of this RoutePolicy.


        :param throttle_policy: The throttle_policy of this RoutePolicy.  # noqa: E501
        :type: ThrottlePolicy
        """

        self._throttle_policy = throttle_policy

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RoutePolicy):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
